version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
#      POSTGRES_HOST: db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: afazyltegi/devops-for-programmers-project-74
    depends_on:
      - db
    command: ["make", "test"]
