version: '3.8'

services:
  app:
    image: afazyltegi/devops-for-programmers-project-74:latest
    build:
      context: .
#      dockerfile: Dockerfile
      dockerfile: ${DOCKERFILE:-Dockerfile}
#    working_dir: /app
#    volumes:
#      - ./app:/app
#    ports:
#      - "8080:8080"
#    command: make dev
    command: ${COMMAND:-make dev}
